name: Nethermind Assignment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all the branches
  push:
    branches: [ "**" ]

jobs:
  unit-test-runner:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@master # THIS IS IMPORTANT
      - uses: actions/setup-python@v3 # THIS IS IMPORTANT
      - uses: actions/setup-go@v4
        with:
          python-version: '3.8'
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Install Sage
        run: |
          echo "Downloading sedge sources..."
          git clone https://github.com/NethermindEth/sedge.git src --branch main --single-branch
          echo "Sources downloaded."
          cd src
          echo "Building sedge..."
          make compile
      - name: Install Go
        run: sudo apt install golang-go
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py38 .
        continue-on-error: true
      - name: Show library versions
        run: |
          python3 --version
          pytest --version
      - name: Run Sedge
        run: |
          echo "running sedge..."
          ./sedge deps install >> $HOME/sedge.logs
          ./sedge generate --logging none -p $HOME /
          full-node --map-all --no-mev-boost --no-validator --network chiado /
          -c lighthouse:sigp/lighthouse:latest -e nethermind:nethermindeth/nethermind:master /
          --el-extra-flag Sync.NonValidatorNode=true --el-extra-flag Sync.DownloadBodiesInFastSync=false /
          --el-extra-flag Sync.DownloadReceiptsInFastSync=false /
          --cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000/ >> $HOME/sedge.logs
          ./sedge run -p . >> $HOME/sedge.logs
      - name: Run Tests
        run: pytest -v tests_unit/
